name: Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-linux-x86-64:
    name: Linux x86-64
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: fdProject
          environment-file: fdProject_env.yml
          auto-activate-base: false

      - name: Verify Conda env
        run: |
          conda info
          conda list
          conda env list
          conda activate fdProject

      - name: Verify installation
        run:
          python Mapper.py --help